#if !canImport(ObjectiveC)
import XCTest

extension ChalkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChalkTests = [
        ("testChalk", testChalk),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChalkTests.__allTests__ChalkTests),
    ]
}
#endif
